In [18]:
import pandas as pd
list=[pd.read_html("http://rates.am/am/armenian-dram-exchange-rates/banks/non-cash/2017/06/01/17-30"),pd.read_html("http://rates.am/am/armenian-dram-exchange-rates/banks/non-cash/2017/06/02/17-30"),pd.read_html("http://rates.am/am/armenian-dram-exchange-rates/banks/non-cash/2017/06/03/17-30"),pd.read_html("http://rates.am/am/armenian-dram-exchange-rates/banks/non-cash/2017/06/04/17-30"),pd.read_html("http://rates.am/am/armenian-dram-exchange-rates/banks/non-cash/2017/06/05/17-30"),pd.read_html("http://rates.am/am/armenian-dram-exchange-rates/banks/non-cash/2017/06/06/17-30"),pd.read_html("http://rates.am/am/armenian-dram-exchange-rates/banks/non-cash/2017/06/07/17-30")]
for data in list:
    print data[2][2:19]

     0                       1    2   3              4       5       6   \
2    1.               Ինեկոբանկ  NaN  23  01 Հնս, 17:30  480.50  483.75
3    2.       ՎՏԲ-Հայաստան Բանկ  NaN  68  01 Հնս, 17:30  480.75  483.25
4    3.               Արցախբանկ  NaN  24  01 Հնս, 17:30     481  484.50
5    4.             Մելլաթ բանկ  NaN   1  01 Հնս, 17:30     480     484
6    5.       Էյչ-Էս-Բի-Սի Բանկ  NaN   9  01 Հնս, 17:30  480.50  484.50
7    6.            Կոնվերս բանկ  NaN  35  01 Հնս, 17:30     480  483.50
8    7.       ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ  NaN  53  01 Հնս, 17:30     480  483.50
9    8.  ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..  NaN  59  01 Հնս, 17:30  480.25  483.75
10   9.              Ամերիաբանկ  NaN  11  01 Հնս, 17:30  479.50  483.50
11  10.             Արմսվիսբանկ  NaN   1  01 Հնս, 17:30     481     484
12  11.              Արդշինբանկ  NaN  53  01 Հնս, 17:30  480.50  483.50
13  12.           ՀԱՅԷԿՈՆՈՄԲԱՆԿ  NaN  49  01 Հնս, 17:30     480  483.50
14  13.     Բիբլոս Բանկ Արմենիա  NaN   5  01 Հնս, 17:30     480     484
15  14.             Անելիք Բանկ  NaN  14  01 Հնս, 17:30     480  483.50
16  15.              ԱՐԱՐԱՏԲԱՆԿ  NaN  48  01 Հնս, 17:30     480  483.50
17  16.               Յունիբանկ  NaN  47  01 Հնս, 17:30     480  483.50
18  17.           Պրոմեթեյ Բանկ  NaN  12  01 Հնս, 17:30     481  483.50

        7      8     9     10     11     12
2      536  544.5  8.40  8.62  614.0  626.0
3      538  543.5  8.44  8.60  615.0  626.0
4      539  546.0  8.40  8.65  615.0  626.0
5      538  546.0   NaN   NaN    NaN    NaN
6   538.50  546.0  8.38  8.63  616.0  626.0
7      538  546.0  8.44  8.63  616.0  624.0
8   537.10  545.1  8.42  8.63  614.1  626.1
9      537  545.0  8.46  8.60  613.0  628.0
10     536  544.0  8.38  8.63  614.5  624.5
11     537  543.0  8.45  8.63  616.0  623.0
12     536  546.0  8.40  8.65  614.0  629.0
13     535  545.0  8.45  8.62  612.0  629.0
14     537  546.0  8.37  8.65  614.0  626.0
15     535  545.0  8.45  8.65    NaN    NaN
16     536  546.0  8.44  8.70  609.0  627.0
17     536  546.0  8.35  8.65  609.0  629.0
18     538  544.0  8.48  8.58  614.0  625.0
     0                       1    2   3              4       5       6   \
2    1.               Արցախբանկ  NaN  24  02 Հնս, 17:31  479.50     484
3    2.             Մելլաթ բանկ  NaN   1  02 Հնս, 17:31  479.50  483.50
4    3.       ՎՏԲ-Հայաստան Բանկ  NaN  68  02 Հնս, 17:31  480.75  483.50
5    4.               Ինեկոբանկ  NaN  23  02 Հնս, 17:31  480.50  483.75
6    5.       Էյչ-Էս-Բի-Սի Բանկ  NaN   9  02 Հնս, 17:31     480     484
7    6.            Կոնվերս բանկ  NaN  35  02 Հնս, 17:31     480  483.50
8    7.       ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ  NaN  53  02 Հնս, 17:31     480  483.50
9    8.              Ամերիաբանկ  NaN  11  02 Հնս, 17:31     480     484
10   9.  ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..  NaN  59  02 Հնս, 17:31  480.25  483.75
11  10.     Բիբլոս Բանկ Արմենիա  NaN   5  02 Հնս, 17:31     480     484
12  11.             Արմսվիսբանկ  NaN   1  02 Հնս, 17:31     481     484
13  12.              ԱՐԱՐԱՏԲԱՆԿ  NaN  48  02 Հնս, 17:31     481     484
14  13.             Անելիք Բանկ  NaN  14  02 Հնս, 17:31  480.50     484
15  14.           ՀԱՅԷԿՈՆՈՄԲԱՆԿ  NaN  49  02 Հնս, 17:31     480     484
16  15.              Արդշինբանկ  NaN  53  02 Հնս, 17:31  480.50  483.50
17  16.           Պրոմեթեյ Բանկ  NaN  12  02 Հնս, 17:31     481  483.50
18  17.               Յունիբանկ  NaN  47  02 Հնս, 17:31     480  483.50

        7      8     9     10     11     12
2      537  545.0  8.45  8.65  615.0  627.0
3      537  545.0   NaN   NaN    NaN    NaN
4      537  548.0  8.42  8.64  614.0  630.0
5   537.50  547.0  8.40  8.63  614.0  626.0
6      537  544.5  8.41  8.66  616.5  625.0
7      537  545.0  8.42  8.62  616.0  624.0
8   536.10  544.1  8.40  8.64  614.1  625.1
9      540  548.0  8.42  8.67  617.0  627.0
10  539.50  547.0  8.48  8.61  614.0  629.0
11     536  545.0  8.40  8.68  615.0  627.0
12     540  546.0  8.46  8.64  617.0  624.0
13     538  548.0  8.47  8.70  611.0  629.0
14     535  545.0  8.47  8.64    NaN    NaN
15     536  546.0  8.48  8.64  612.0  630.0
16     536  546.0  8.37  8.65  614.0  629.0
17     538  545.0  8.48  8.60  616.0  626.0
18     538  548.0  8.40  8.70  609.0  629.0
     0                       1    2   3              4       5       6   \
2    1.               Ինեկոբանկ  NaN  23  03 Հնս, 17:30  480.50     484
3    2.       ՎՏԲ-Հայաստան Բանկ  NaN  68  03 Հնս, 17:30  480.75  483.50
4    3.               Արցախբանկ  NaN  24  03 Հնս, 17:30  479.50     484
5    4.             Մելլաթ բանկ  NaN   1  03 Հնս, 17:30  479.50  483.50
6    5.       Էյչ-Էս-Բի-Սի Բանկ  NaN   9  03 Հնս, 17:30     480     484
7    6.            Կոնվերս բանկ  NaN  35  03 Հնս, 17:30     480  483.50
8    7.  ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..  NaN  59  03 Հնս, 17:30  480.25  483.75
9    8.       ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ  NaN  53  03 Հնս, 17:30     481  483.50
10   9.              Ամերիաբանկ  NaN  11  03 Հնս, 17:30     480     484
11  10.              ԱՐԱՐԱՏԲԱՆԿ  NaN  48  03 Հնս, 17:30     481     484
12  11.             Անելիք Բանկ  NaN  14  03 Հնս, 17:30  480.50     484
13  12.              Արդշինբանկ  NaN  53  03 Հնս, 17:30  480.50  483.50
14  13.             Արմսվիսբանկ  NaN   1  03 Հնս, 17:30     481     484
15  14.           ՀԱՅԷԿՈՆՈՄԲԱՆԿ  NaN  49  03 Հնս, 17:30     480     484
16  15.     Բիբլոս Բանկ Արմենիա  NaN   5  03 Հնս, 17:30     480     484
17  16.               Յունիբանկ  NaN  47  03 Հնս, 17:30     480  483.50
18  17.           Պրոմեթեյ Բանկ  NaN  12  03 Հնս, 17:30     481     484

        7      8     9     10     11     12
2      538  548.0  8.38  8.62  615.0  628.0
3      537  548.0  8.42  8.64  613.0  631.0
4      538  547.0  8.45  8.65  615.0  627.0
5      537  545.0   NaN   NaN    NaN    NaN
6      539  548.0  8.34  8.69  614.0  626.0
7      539  547.0  8.45  8.65  615.0  624.0
8   539.50  547.0  8.48  8.61  614.0  629.0
9   536.10  544.1  8.40  8.64  614.1  625.1
10     540  548.0  8.40  8.65  615.5  625.5
11     534  551.0  8.44  8.70  609.0  631.0
12     535  545.0  8.47  8.64    NaN    NaN
13     536  546.0  8.37  8.65  614.0  629.0
14     540  546.0  8.46  8.64  617.0  624.0
15     535  550.0  8.42  8.64  612.0  630.0
16     536  545.0  8.40  8.68  615.0  627.0
17     538  548.0  8.40  8.70  609.0  629.0
18     538  547.0  8.46  8.64  616.0  626.0
     0                       1    2   3              4       5       6   \
2    1.             Մելլաթ բանկ  NaN   1  04 Հնս, 17:30  479.50  483.50
3    2.               Արցախբանկ  NaN  24  04 Հնս, 17:30  479.50     484
4    3.               Ինեկոբանկ  NaN  23  04 Հնս, 17:30  480.50     484
5    4.       ՎՏԲ-Հայաստան Բանկ  NaN  68  04 Հնս, 17:30  480.75  483.50
6    5.       Էյչ-Էս-Բի-Սի Բանկ  NaN   9  04 Հնս, 17:30     480     484
7    6.            Կոնվերս բանկ  NaN  35  04 Հնս, 17:30     480  483.50
8    7.              Ամերիաբանկ  NaN  11  04 Հնս, 17:30     480     484
9    8.  ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..  NaN  59  04 Հնս, 17:30  480.25  483.75
10   9.       ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ  NaN  53  04 Հնս, 17:30     481  483.50
11  10.             Արմսվիսբանկ  NaN   1  04 Հնս, 17:30     481     484
12  11.     Բիբլոս Բանկ Արմենիա  NaN   5  04 Հնս, 17:30     480     484
13  12.             Անելիք Բանկ  NaN  14  04 Հնս, 17:30  480.50     484
14  13.              ԱՐԱՐԱՏԲԱՆԿ  NaN  48  04 Հնս, 17:30     481     484
15  14.              Արդշինբանկ  NaN  53  04 Հնս, 17:30  480.50  483.50
16  15.           ՀԱՅԷԿՈՆՈՄԲԱՆԿ  NaN  49  04 Հնս, 17:30     480     484
17  16.               Յունիբանկ  NaN  47  04 Հնս, 17:30     480  483.50
18  17.           Պրոմեթեյ Բանկ  NaN  12  04 Հնս, 17:30     481     484

        7      8     9     10     11     12
2      537  545.0   NaN   NaN    NaN    NaN
3      538  547.0  8.45  8.65  615.0  627.0
4      538  548.0  8.38  8.62  615.0  628.0
5      537  548.0  8.42  8.64  613.0  631.0
6      539  548.0  8.34  8.69  614.0  626.0
7      539  547.0  8.45  8.65  615.0  624.0
8      540  548.0  8.40  8.65  615.5  625.5
9   539.50  547.0  8.48  8.61  614.0  629.0
10  536.10  544.1  8.40  8.64  614.1  625.1
11     540  546.0  8.46  8.64  617.0  624.0
12     536  545.0  8.40  8.68  615.0  627.0
13     535  545.0  8.47  8.64    NaN    NaN
14     534  551.0  8.44  8.70  609.0  631.0
15     536  546.0  8.37  8.65  614.0  629.0
16     535  550.0  8.42  8.64  612.0  630.0
17     538  548.0  8.40  8.70  609.0  629.0
18     538  547.0  8.46  8.64  616.0  626.0
     0                       1    2   3              4       5       6   \
2    1.               Արցախբանկ  NaN  24  05 Հնս, 17:30  481.50     484
3    2.       ՎՏԲ-Հայաստան Բանկ  NaN  68  05 Հնս, 17:30  480.75  483.50
4    3.               Ինեկոբանկ  NaN  23  05 Հնս, 17:30  480.50     484
5    4.             Մելլաթ բանկ  NaN   1  05 Հնս, 17:30     480     484
6    5.       Էյչ-Էս-Բի-Սի Բանկ  NaN   9  05 Հնս, 17:30     480     484
7    6.            Կոնվերս բանկ  NaN  35  05 Հնս, 17:30     480  483.50
8    7.       ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ  NaN  53  05 Հնս, 17:30     480  483.50
9    8.              Ամերիաբանկ  NaN  11  05 Հնս, 17:30     480     484
10   9.  ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..  NaN  59  05 Հնս, 17:30  480.50     484
11  10.             Արմսվիսբանկ  NaN   1  05 Հնս, 17:30     481     484
12  11.             Անելիք Բանկ  NaN  14  05 Հնս, 17:30  480.50     484
13  12.           ՀԱՅԷԿՈՆՈՄԲԱՆԿ  NaN  49  05 Հնս, 17:30     480     484
14  13.     Բիբլոս Բանկ Արմենիա  NaN   5  05 Հնս, 17:30     480     484
15  14.              Արդշինբանկ  NaN  53  05 Հնս, 17:30     481     484
16  15.              ԱՐԱՐԱՏԲԱՆԿ  NaN  48  05 Հնս, 17:30  480.50     484
17  16.               Յունիբանկ  NaN  47  05 Հնս, 17:30     480  483.50
18  17.           Պրոմեթեյ Բանկ  NaN  12  05 Հնս, 17:30  481.50     484

        7      8     9     10     11     12
2      538  547.0  8.45  8.65  615.0  627.0
3      539  546.0  8.42  8.64  616.0  627.0
4      537  546.0  8.38  8.63  615.0  626.0
5      540  548.0   NaN   NaN    NaN    NaN
6      539  547.0  8.40  8.65  616.0  624.5
7      539  547.0  8.44  8.63  616.0  624.0
8   539.10  547.1  8.41  8.65  614.1  626.1
9      539  547.0  8.38  8.63  619.0  629.0
10  538.50  547.0  8.46  8.59  615.0  630.0
11     538  544.0  8.44  8.62  618.0  625.0
12     537  547.0  8.46  8.64    NaN    NaN
13     537  547.0  8.46  8.64  614.0  632.0
14     538  548.0  8.38  8.66  614.0  626.0
15     538  548.0  8.40  8.65  614.0  629.0
16     537  547.0  8.45  8.70  612.0  630.0
17     538  548.0  8.40  8.70  609.0  629.0
18     540  546.0  8.48  8.58  617.0  627.0
     0                       1    2   3              4       5       6   \
2    1.       Էյչ-Էս-Բի-Սի Բանկ  NaN   9  06 Հնս, 17:31  480.50  484.50
3    2.       ՎՏԲ-Հայաստան Բանկ  NaN  68  06 Հնս, 17:30  481.25  483.75
4    3.               Ինեկոբանկ  NaN  23  06 Հնս, 17:30  481.50  484.50
5    4.               Արցախբանկ  NaN  24  06 Հնս, 17:30  482.50     484
6    5.             Մելլաթ բանկ  NaN   1  06 Հնս, 17:30     480     484
7    6.            Կոնվերս բանկ  NaN  35  06 Հնս, 17:30     480  483.50
8    7.              Ամերիաբանկ  NaN  11  06 Հնս, 17:30  480.50  484.50
9    8.  ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..  NaN  59  06 Հնս, 17:30  481.50  484.50
10   9.       ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ  NaN  53  06 Հնս, 17:30  480.50  483.50
11  10.           ՀԱՅԷԿՈՆՈՄԲԱՆԿ  NaN  49  06 Հնս, 17:30     481  484.50
12  11.     Բիբլոս Բանկ Արմենիա  NaN   5  06 Հնս, 17:30     481  484.50
13  12.             Անելիք Բանկ  NaN  14  06 Հնս, 17:30     481  484.50
14  13.             Արմսվիսբանկ  NaN   1  06 Հնս, 17:30     481     484
15  14.              Արդշինբանկ  NaN  53  06 Հնս, 17:30  481.50     484
16  15.              ԱՐԱՐԱՏԲԱՆԿ  NaN  48  06 Հնս, 17:30  481.50  484.50
17  16.               Յունիբանկ  NaN  47  06 Հնս, 17:30     481     484
18  17.           Պրոմեթեյ Բանկ  NaN  12  06 Հնս, 17:30  481.50  484.50

        7      8     9     10     11     12
2   539.50  547.5  8.40  8.65  619.5  628.5
3      539  545.5  8.44  8.60  618.0  630.0
4      539  547.0  8.40  8.60  618.0  629.0
5      539  547.0  8.45  8.70  617.0  630.0
6      540  548.0   NaN   NaN    NaN    NaN
7      539  547.0  8.46  8.66  619.0  627.0
8   539.50  547.5  8.38  8.63  617.0  627.0
9   539.50  547.0  8.46  8.60  616.0  631.0
10  539.10  547.1  8.43  8.65  617.1  629.1
11     538  548.0  8.47  8.65  615.0  633.0
12     540  548.0  8.40  8.68  618.0  630.0
13     539  549.0  8.45  8.63    NaN    NaN
14     540  546.0  8.47  8.65  619.0  626.0
15     539  549.0  8.40  8.65  618.0  633.0
16     538  548.0  8.46  8.70  613.0  631.0
17     539  549.0  8.40  8.70  613.0  633.0
18     540  546.0  8.48  8.59  618.0  628.0
     0                       1    2   3              4       5       6   \
2    1.       Էյչ-Էս-Բի-Սի Բանկ  NaN   9  07 Հնս, 17:31  480.50  484.50
3    2.       ՎՏԲ-Հայաստան Բանկ  NaN  68  07 Հնս, 17:30  481.25  483.75
4    3.               Արցախբանկ  NaN  24  07 Հնս, 17:30  482.25     484
5    4.               Ինեկոբանկ  NaN  23  07 Հնս, 17:30  481.50  484.25
6    5.             Մելլաթ բանկ  NaN   1  07 Հնս, 17:30  480.50  484.50
7    6.            Կոնվերս բանկ  NaN  35  07 Հնս, 17:30     481  484.50
8    7.  ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..  NaN  59  07 Հնս, 17:30     481  484.50
9    8.              Ամերիաբանկ  NaN  11  07 Հնս, 17:30  480.50  484.50
10   9.       ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ  NaN  53  07 Հնս, 17:30  480.50     484
11  10.              ԱՐԱՐԱՏԲԱՆԿ  NaN  48  07 Հնս, 17:30  481.50  484.50
12  11.             Արմսվիսբանկ  NaN   1  07 Հնս, 17:30     481     484
13  12.     Բիբլոս Բանկ Արմենիա  NaN   5  07 Հնս, 17:30     481  484.50
14  13.           ՀԱՅԷԿՈՆՈՄԲԱՆԿ  NaN  49  07 Հնս, 17:30     481  484.50
15  14.              Արդշինբանկ  NaN  53  07 Հնս, 17:30  481.50     484
16  15.             Անելիք Բանկ  NaN  14  07 Հնս, 17:30     481  484.50
17  16.               Յունիբանկ  NaN  47  07 Հնս, 17:30     481     484
18  17.           Պրոմեթեյ Բանկ  NaN  12  07 Հնս, 17:30     481     484

        7      8     9     10     11     12
2   539.50  547.5  8.42  8.67  618.0  627.0
3      540  546.0  8.45  8.65  618.0  630.0
4      538  546.0  8.45  8.65  617.0  630.0
5      538  546.0  8.40  8.62  617.0  629.0
6      540  548.0   NaN   NaN    NaN    NaN
7      537  545.0  8.45  8.65  619.0  627.0
8   537.50  546.0  8.47  8.61  616.0  631.0
9   538.50  546.5  8.39  8.64  619.0  629.0
10  537.10  545.1  8.41  8.64  616.1  628.1
11     537  547.0  8.47  8.70  614.0  631.0
12     538  544.0  8.44  8.62  618.0  625.0
13     539  548.0  8.41  8.69  617.0  628.0
14     536  546.0  8.47  8.65  615.0  633.0
15     538  548.0  8.40  8.68  617.0  632.0
16     538  548.0  8.46  8.62    NaN    NaN
17     539  549.0  8.40  8.70  613.0  633.0
18     538  546.0  8.47  8.58  618.0  628.0

In [2]:
import re
import requests
url1="https://www.bloomberg.com/quote/SPX:IND"
response = requests.get(url1)
data = response.text
data1 = re.sub(r'<|>'," ",data)
output=re.findall('"price"\s*([0-9]\S*)',data1)
print output

[u'2,429.39']

In [4]:
import json
input='''[
    {
    "Movie":"Game of Thrones",
    "Actor":"Peter Dinklage",
    "Role":"Tyrion Lannister"    
    },
    {
    "Movie":"Vikings",
    "Actor":"Travis Fimmel",
    "Role":"Ragnar Lothbrok"  
    },
    {
    "Movie":"The last Kingdom",
    "Actor":{
            "Young Uhtred":"Tom Taylor",
            "Not that young Uhtred":"Alexander Dreymon"
            },
    "Role":"Uhtred of Bebbanburg"
    }
]'''
inpt=json.loads(input)
for x in inpt:
        print"Movie:", x['Movie']
        print "Role:", x["Role"]
        if type(x["Actor"]) == dict:
                print "Actor 1: " , x["Actor"]['Young Uhtred']
                print "Actor 2: " , x["Actor"]['Not that young Uhtred']
        else:
            print "Actor:", x["Actor"], "\n"

Movie: Game of Thrones
Role: Tyrion Lannister
Actor: Peter Dinklage

Movie: Vikings
Role: Ragnar Lothbrok
Actor: Travis Fimmel

Movie: The last Kingdom
Role: Uhtred of Bebbanburg
Actor 1:  Tom Taylor
Actor 2:  Alexander Dreymon

In [21]:
import pandas as pd
import matplotlib.pyplot as plt
pas_csv=pd.read_csv("AirPassengers.csv")
pas_csv1=pas_csv.Passengers
print pas_csv1

0      112
1      118
2      132
3      129
4      121
5      135
6      148
7      148
8      136
9      119
10     104
11     118
12     115
13     126
14     141
15     135
16     125
17     149
18     170
19     170
20     158
21     133
22     114
23     140
24     145
25     150
26     178
27     163
28     172
29     178
      ...
114    491
115    505
116    404
117    359
118    310
119    337
120    360
121    342
122    406
123    396
124    420
125    472
126    548
127    559
128    463
129    407
130    362
131    405
132    417
133    391
134    419
135    461
136    472
137    535
138    622
139    606
140    508
141    461
142    390
143    432
Name: Passengers, dtype: int64

In [23]:
import re
import requests
url3="http://quotes.toscrape.com/"
response = requests.get(url3)
nxt=response.text
nxt1=re.findall('<a href\s*="\S+"\s*>Next', nxt)
nxt2=re.sub(r'^(.*?)/'," http://quotes.toscrape.com/",str(nxt1))
nxt3=re.sub(r'">Next'," ",nxt2)
print nxt3

 http://quotes.toscrape.com/page/2/ ']